Repository BakxY/DiscordApexBot, pull requests merged in 2022-02, with the labels that each got.

#6 fix for token files
  main.py
Labels: bug fix

#8 Bugfix with command handling
  main.py
  src/banners/Valkyrie.jpg
Labels: bug fix

#9 Platform independent API req.
  main.py
  src/rank/Diamond3.png
Labels: enhancement

#16 Added API not reachable handling
  main.py
  src/banners/Loba.jpg
Labels: bug

#21 Added handling for mentions of the bot
  main.py
Labels: bug

#22 add log.py with functions
  __pycache__/log.cpython-39.pyc
  __pycache__/rank.cpython-39.pyc
  log.py
  main.py
  src/log/latest.log
Labels: enhancement

#24 Added status command
  main.py
  src/ApexServer.png
Labels: enhancement

#26 updated log.py
  log.py
Labels: enhancement
